# Default scene settings. This script default is 1 (IsaacSim), so if you change
# the meters per unit or up axis, you need to alter the coordinates and rotations.

# IsaacSim default is 1, Code is 0.01
stage_unit_setting:
  settings.set_stage_meters_per_unit:
    meters_per_unit: 1

# IsaacSim default is "Z"", Code is "Y"
stage_up_axis_setting:
  settings.set_stage_up_axis:
    up_axis: "Z"

# Create the camera and render product
camera:
  create.camera:
    position: [-10, -10, 3]
    rotation: [0, 0, 0]

render_product:
  create.render_product:
    camera: camera
    resolution: [1280, 720]

# Load the scene
warehouse:
  create.from_usd:
    usd: "omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.0/Isaac/Environments/Simple_Warehouse/full_warehouse.usd"

# Select the objects in the scene
forklift:
  create.group:
    items: ["/Root/forklift"]

floor:
  get.prims:
    semantics: [["class", "floor"]]

racks_and_walls:
  get.prims:
    semantics: [["class", "rack"], ["class", "wall"]]

# Create the writer and initialize
writer:
  writers.get:
    name: "KittiWriter"
    init_params:
      output_dir: "/workspaces/synthetic-data-examples/.out/Warehouse"

writer_attach:
  writer.attach:
    render_products: render_product

# Set the trigger as on_frame
trigger:
  trigger.on_frame:
    max_execs: 50
    rt_subframes: 3

# When the trigger executes, run the following logic
with_trigger:
  with.trigger:
    with.camera:
      # move the camera around and rotate
      modify.pose:
        position:
          distribution.uniform:
            lower: [-23.6, -3, 2.5]
            upper: [3.03, 3, 5.0]
        rotation:
          distribution.uniform:
            lower: [0, -30, -120]
            upper: [0, -10, -60]

    # move the forklift around and rotate
    # with.forklift:
    #   modify.pose:
    #     rotation:
    #       distribution.uniform:
    #         lower: [0, 0, 0]
    #         upper: [0, 0, 359]
    #   randomizer.scatter_2d:
    #     surface_prims: floor
    #     no_coll_prims: racks_and_walls
    #     check_for_collisions: True

    # create and scatter cones
    cone_instance:
      randomizer.instantiate:
        paths:
          [
            "omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.0/Isaac/Environments/Simple_Warehouse/Props/S_TrafficCone.usd",
          ]
        size: 50
        mode: "point_instance"

    with.cone_instance:
      randomizer.scatter_2d:
        seed: 0
        surface_prims: floor
        no_coll_prims: racks_and_walls
        check_for_collisions: True

    # create and scatter wet floor signs
    wet_floor_sign_instance:
      randomizer.instantiate:
        paths:
          [
            "omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.0/Isaac/Environments/Simple_Warehouse/Props/S_WetFloorSign.usd",
          ]
        size: 50
        mode: "scene_instance"

    with.wet_floor_sign_instance:
      randomizer.scatter_2d:
        seed: 1
        surface_prims: floor
        no_coll_prims: racks_and_walls
        check_for_collisions: True
